### ISSUE TITLE
Own dataset form multivariate regression task

### ISSUE THREAD

**Issue by IKetchup** [Nixtla/neuralforecast#1068]
### What happened + What you expected to happen

Hello, thank you for your amazing work. I would like to use it in my research with timeseries.
I woud like to train a model to predict 3D timeseries from other  differents 3D timeseries. My goal is to use timeseries of shape (batch_size, len_size, input_features) to predict differents timeseries of shape (batch_size, len_size, output_features) with input_features different from output_features (no commun features). Is it possible to do so as this type of problem is not exaclty seen as forcasting and if possible how should I start ?
Thanks in advance

* sorry for posting my question here the invitation to the Slack doesnt work

### Versions / Dependencies

.

### Reproduction script

.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by elephaint** [comment]
THanks for the kind words.

Technically NF should be able to handle this scenario but I don't think we currently have an algorithm that fully supports what you're trying to do. If I understand correctly, you want to use some set of features to predict another set of features, where both sets of features may or may not consist (partially?) of timeseries. If none of the features contain timeseries, obviously the best choice is to just treat this as a regression problem with multiple outputs. Then, you're better of not treating this as a forecasting problem.

Now, you could implement this yourself in a model in NF; it needs to be a multivariate model (it consumes multiple timeseries / features and outputs multiple timeseries/features). However, since you want the input features/series different from the output features/series, you'd have to exclude the input series from the algorithm, and use a set of different exogenous features as input features. These input features would then serve to predict the output series. The issue is that we don't offer such a model at the moment - you'd need a multivariate model where you can also exclude the insample_y (i.e. the lagged target variables) in order to create a distinction between input- and output features. So, your best bet using a custom model in NF would be to:

1. Follow our guide on [adding a model](https://nixtlaverse.nixtla.io/neuralforecast/examples/how_to_add_models.html).
2. Start with a copy of `TSMixerx`.
3. Remove the `insample_y` part of TSMixerx.
4. Now, when training, create a dataset that contains exogenous features and time series targets. By having removed the `insample_y` part, the algorithm will not consider any (lagged) target variables in the training/prediction. This is what you want. It will only use the exogenous variables during training. The target will be the time series targets. I think with this setup you will achieve what you want and at this moment it's the easiest way to do it with NF until we offer a multivariate model that allows to exclude `insample_y` by default (some of our univariate models do offer this functionality already, for example `NHITS` allows to set a hyperparameter `exclude_insample_y = True`, which will cause the lagged target variable to be ignored during training).

Hope this is a bit clear and let me know if this answers your question.

**Comment by 4444zyf** [comment]
I think that the Informer perhaps support Single-Single, Multi-Multi, Multi-Single problems with their original implements.
