### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by beergil** [Nixtla/neuralforecast#445]
What is unique id all about?

**Comment by kdgutier** [comment]
Hi @beergil,

NeuralForecast models are "global" models, in the sense that they share parameters to predict a set of time series simultaneously rather than single series. This technique is also called [cross-learning](https://www.sciencedirect.com/science/article/pii/S0169207020301850) in the forecasting literature. 

The normal input for a NeuralForecast model is a pandas dataframe `Y_df` with a minimal of `['unique_id', 'ds', 'y']` columns, where `'unique_id'` identifies different series, `'ds'` identifies the time stamp, and `'y'` the target variable.
