### ISSUE TITLE
NHITS stack_types ‘seasonality’ and ‘trend’ not recognized

### ISSUE THREAD

**Issue by carlosg-m** [Nixtla/neuralforecast#530]
NHITS stack_types ‘seasonality’ and ‘trend’ not recognized

**Comment by candalfigomoro** [comment]
@kdgutier
I think the problem is that in the NHITS documentation https://nixtla.github.io/neuralforecast/models.nhits.html we read `stack_types: List[str], List of stack types. Subset from [‘seasonality’, ‘trend’, ‘identity’].` Moreover, some parameters are not documented (e.g. `n_freq_downsample` and other params are not documented). In general, the API reference could be improved (sometimes I look at the Darts documentation, e.g. https://unit8co.github.io/darts/generated_api/darts.models.forecasting.nhits.html as it better explain the parameters).
