### ISSUE TITLE
How to incrementally retrain model with new data

### ISSUE THREAD

**Issue by rnjv** [Nixtla/neuralforecast#535]
Given streaming data, how do we retrain on new smaller batch of data on previously trained model.

Is this possible?

**Comment by rnjv** [comment]
Will core.fit and retraining by batches reduce the memory requirements, currently memory requirements looks heavy.

**Comment by kdgutier** [comment]
Hey @rnjv,

The memory requirements depend on the models.

If you are using Recurrent-based models like LSTM, TCN, GRU you can use the `inference_input_size` parameter to reduce the memory usage during inference. What the parameter does is trimming the length of the time series at the time of the prediction.

**Comment by rnjv** [comment]
Is doing something like this reliable?

`nf = NeuralForecast(models=models, freq='1min')
for i in range(0,df.shape[0], 60000):
  dft = df[i:i+60000-1].copy()
  nf.fit(df=dft)`

**Comment by kdgutier** [comment]
Hey @rnjv,

If you are using panel data, your approach will not work.

If you are using a single series you could try to only use 60,000 windows that way, although you can achieve the same results with the `inference_input_size` parameter.

**Comment by rnjv** [comment]
> Hey @rnjv,
> 
> To save and retrain a model you can use `core.save` and `core.load` methods. Here is a [save and load tutorial](https://nixtla.github.io/neuralforecast/examples/save_load_models.html).
> 
> Calling a `core.fit` on the loaded model will retrain it incrementally.

How would you suggest training panel data incrementally? As I understood - one loads the saved model; load the slice of data the model has not been trained on; and we would get the updated model.

**Comment by cchallu** [comment]
Hi @rnjv .  What model/s are you using?

The `save` and `load` methods will work regardless of the number of time series of the data.

We have updated the windows-based models (TFT, NHITS, etc) so that the length of the time series does not increase the memory requirement (other than fitting the data). For recurrent models (RNN, LSTM, etc), use `input_size` and `inference_input_size` to reduce the memory requirement (truncated backprogapation).

We mostly recommend training on batches (with `save` and `load`) only for updating a production model with the latest data.
