### ISSUE TITLE
How to forecast values for future dates?

### ISSUE THREAD

**Issue by SujayC66** [Nixtla/neuralforecast#983]
### Description

Currently .predict gives only prediction on test data. How can we forecast values for future dates?

**Comment by elephaint** [comment]
Do you have a piece of (standalone) code so that I can understand what you are trying to achieve?

You don't need to supply a test data set. You can just call predict to forecast future values, as is explained in the [Quick Start guide](https://nixtlaverse.nixtla.io/neuralforecast/examples/getting_started.html)

**Comment by SujayC66** [comment]
Thanks. I was confused since the code in tutorial shown in repo was giving predictions.
fcst = NeuralForecast(models=[model], freq='M')
fcst.fit(df=Y_train_df, static_df=AirPassengersStatic, val_size=12)
forecasts = fcst.predict(futr_df=Y_test_df)
Thank you so much.
